"""empty message

Revision ID: bc5f4c410ba2
Revises: 
Create Date: 2022-11-29 22:00:06.121227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc5f4c410ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Username', sa.String(length=15), nullable=False),
    sa.Column('Name', sa.String(length=10), nullable=False),
    sa.Column('Surname', sa.String(length=15), nullable=False),
    sa.Column('Email', sa.String(length=30), nullable=False),
    sa.Column('Password', sa.String(length=45), nullable=False),
    sa.Column('Role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Username')
    )
    op.create_table('Events',
    sa.Column('EventId', sa.Integer(), nullable=False),
    sa.Column('EventName', sa.String(length=15), nullable=False),
    sa.Column('Time', sa.DATETIME(), nullable=False),
    sa.Column('City', sa.String(length=15), nullable=False),
    sa.Column('Location', sa.String(length=15), nullable=False),
    sa.Column('MaxTickets', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['Username'], ['Users.Username'], ),
    sa.PrimaryKeyConstraint('EventId')
    )
    op.create_table('Tickets',
    sa.Column('TicketId', sa.Integer(), nullable=False),
    sa.Column('Price', sa.Integer(), nullable=False),
    sa.Column('IsBooked', sa.Boolean(), nullable=False),
    sa.Column('IsPaid', sa.Boolean(), nullable=False),
    sa.Column('Line', sa.Integer(), nullable=True),
    sa.Column('Place', sa.Integer(), nullable=True),
    sa.Column('Username', sa.String(length=15), nullable=True),
    sa.Column('EventId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EventId'], ['Events.EventId'], ),
    sa.ForeignKeyConstraint(['Username'], ['Users.Username'], ),
    sa.PrimaryKeyConstraint('TicketId')
    )
    op.drop_table('users')
    op.drop_table('tickets')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('EventId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('EventName', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Time', mysql.DATETIME(), nullable=False),
    sa.Column('City', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Location', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('MaxTickets', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Username', mysql.VARCHAR(length=15), nullable=True),
    sa.ForeignKeyConstraint(['Username'], ['users.Username'], name='events_ibfk_1'),
    sa.PrimaryKeyConstraint('EventId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tickets',
    sa.Column('TicketId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IsBooked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('IsPaid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Line', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Place', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Username', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('EventId', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['EventId'], ['events.EventId'], name='tickets_ibfk_2'),
    sa.ForeignKeyConstraint(['Username'], ['users.Username'], name='tickets_ibfk_1'),
    sa.PrimaryKeyConstraint('TicketId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('Username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('Surname', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('Password', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('Role', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Username'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Tickets')
    op.drop_table('Events')
    op.drop_table('Users')
    # ### end Alembic commands ###
